name: MLOps Pipeline

on:
  push:
    branches:
      - main
      - diffrent_model  # Hoặc nhánh bạn đang làm việc trên
  pull_request:
    branches:
      - main  # Hoặc nhánh bạn đang làm việc trên
      - diffrent_model
jobs:
  build:
    runs-on: ubuntu-latest #windows-latest

    steps:
    # Kiểm tra code từ repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Thiết lập Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    # Cài đặt dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Chạy kiểm thử
    - name: Run tests
      run: pytest tests/

    # Chạy script huấn luyện mô hình
    - name: Train and save model
      run: python src/train.py

    # Lưu mô hình đã huấn luyện như một artifact
    - name: Save trained model artifact
      uses: actions/upload-artifact@v3
      with:
        name: trained_model
        path: models/
